apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../modules/pipelines
  - ../../modules/workbench
  - ../../modules/redis
  - ../../modules/inference/granite-3-1-2b
  - ../../modules/minio
  - ../../modules/serving-runtime/granite
  - ../../modules/grafana
  - ../../modules/trustyai-guardrails-components
