apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/acicfede/mlops-platform//modules/monitoring-tools/grafana/v1

patches:
  - target:
      kind: Deployment
      name: mlflow-server
    patch: |
      - op: remove
        path: /spec
