apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cyberark-demo

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../chain/chain-1


patchesStrategicMerge:
  - patch-dspa.yaml
