apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cyberark-demo

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../operators/external-secret-operator
  - ../../modules/minio

