apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../modules/workbench
  - ../../modules/minio
  - ../../modules/pipelines
  - ../../modules/mlflow
  - ../../modules/inference/granite-3-1-2b
  - ../../modules/serving-runtime/granite-3-1-2b

  
