apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-team-a

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../operators/redis
  - ../../chain/chain-1

patchesStrategicMerge:
  - og-patch.yaml
  - patch-dspa.yaml

