apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-team-a

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../chain/chain-a

# Variabili
vars:
  - name: OP_NAMESPACE
    objref:
      kind: Namespace
      name: mlops-team-a
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
