apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-team-a

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../operators/redis      # ðŸ‘ˆ PRIMA lâ€™Operator
  - ../../chain/chain-a       # ðŸ‘ˆ POI i moduli che usano Redis

