apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-team-c

resources:
  - namespace.yaml
  - ../../chain/chain-b
  - ../../modules/grafana/

patches:
  - overlays/disable-mlflow
