apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gibberish-detector.yml
  - guardrails-detector-runtime-hap.yml
  - guardrails-orchestrator.yml
  - ibm-hate-and-profanity-detector.yml
  - jailbreak-detector.yml
  - model_storage_container.yml
  - phi3.yml
  - rbac-mlopsuser-mn.yml
