apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-team-b

resources:
  - namespace.yaml
  - rbac/namespace-access.yaml
  - ../../chain/chain-b


patchesStrategicMerge:
  - og-patch.yaml
