apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/acicfede/mlops-platform//modules/workbench/v1
  - github.com/acicfede/mlops-platform//modules/pipelines/v1
  - ../../modules/grafana/

  
