apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - sa-token-refresher.yaml
  - grafana.yaml
  - datasource-prometheus.yaml
  - grafana-ds-mlflow.yaml
  - grafana-dashboard-providers.yaml
  - secret-prometheus-token.yaml
  - rbac-token-refresher.yaml
  - cronjob-token-refresher.yaml
  - rbac-grafana-prometheus.yaml



generatorOptions:
  disableNameSuffixHash: true
